// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "../messageTypes/ClientMessage/ChatMessage";
import type { ConnectionPayloadMessage } from "../messageTypes/ClientMessage/ConnectionPayloadMessage";

export type ClientMessage = { ChatMessage: ChatMessage } | { ConnectionPayloadMessage: ConnectionPayloadMessage };