// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./messageTypes/ChatMessage";

export type ClientMessages = { ChatMessage: ChatMessage };

type MessageOf<T> = T extends keyof ClientMessages ? ClientMessages[T]: never;

export type MessageHandler = {
	[key in keyof ClientMessages]: (arg: MessageOf<key>) => void;
}